apiVersion: apps/v1
kind: Deployment
metadata:
  name: movie-reviews-tracker-deployment
  labels:
    app: movie-reviews-tracker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: movie-reviews-tracker
  template:
    metadata:
      labels:
        app: movie-reviews-tracker
    spec:
      containers:
      - name: movie-reviews-tracker
        image: maeldieudonne/mlops:test
        ports:
        - containerPort: 8000
        command: ["/bin/bash", "-c"]
        args:
        - |
          python -m setup.db_init &&
          python scheduler.py &
          streamlit run streamlit.py \
            --server.port 8000 \
            --server.enableCORS false \
            --server.enableXsrfProtection false
        envFrom:
        - secretRef:
            name: movie-reviews-tracker-credentials
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 10
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 10
