apiVersion: apps/v1
kind: Deployment
metadata:
  name: movies-api-deployment
  labels:
    app: movies-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: movies-api
  template:
    metadata:
      labels:
        app: movies-api
    spec:
      containers:
      - name: movies-api
        image: maeldieudonne/mlops:test
        ports:
        - containerPort: 8000
        command: ["/bin/bash", "-c"]
        args:
        - |
          poetry run python -m setup.db_init &&
          poetry run python scheduler.py &
          uvicorn api:app --host 0.0.0.0 --port 8000 --reload
        envFrom:
        - secretRef:
            name: app-credentials
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 10
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 10
