apiVersion: v1
kind: Service
metadata:
  name: movie-reviews-tracker-service
spec:
  selector:
    app: movie-reviews-tracker
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: LoadBalancer
