apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-movie-reviews-tracker-deployment
  labels:
    app: test-movie-reviews-tracker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-movie-reviews-tracker
  template:
    metadata:
      labels:
        app: test-movie-reviews-tracker
    spec:
      containers:
      - name: test-movie-reviews-tracker
        image: maeldieudonne/mlops:test
        command: ["/bin/bash", "-c"]
        args:
        - |
          poetry run python -m setup.db_init &&
          poetry run python scheduler.py
        envFrom:
        - secretRef:
            name: test-movie-reviews-credentials
