name: Build and Deploy Docker Container

on:
  push:
    branches:
      - dev-frontend

jobs:
  build:
    runs-on: ubuntu-latest

    steps:        
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to DockerHub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Remove existing Docker image (if any)
        run: docker rmi -f maeldieudonne/mlops:testap11 || true

      - name: Build Docker image
        run: |
          docker build --no-cache --pull \
            -t maeldieudonne/mlops:testap11 .

      - name: Push Docker image
        run: docker push maeldieudonne/mlops:testap11